
const SummaryData =
    [
        {
            "location": "Antlion Cave",
            "hitPoints": 1000,
            "attackMultiplier": 2,
            "attackPercent": 85,
            "attackPower": 11,
            "defense": 2,
            "magicDefense": 0,
            "minSpeed": 5,
            "maxSpeed": 5,
            "spellPower": 1,
            "valMagicDef": 170,
            "valDefense": "5 0%x0"
        },
        {
            "location": "Asura (Feymarch)",
            "hitPoints": 23000,
            "attackMultiplier": 10,
            "attackPercent": 99,
            "attackPower": 134,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 66,
            "maxSpeed": 66,
            "spellPower": 69,
            "valMagicDef": 255,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Baigan (Baron Castle 1)",
            "hitPoints": 4200,
            "attackMultiplier": 4,
            "attackPercent": 99,
            "attackPower": 52,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 8,
            "maxSpeed": 8,
            "spellPower": 9,
            "valMagicDef": 254,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Baron Guards (Baron Inn 1)",
            "hitPoints": 400,
            "attackMultiplier": 3,
            "attackPercent": 99,
            "attackPower": 46,
            "defense": 1,
            "magicDefense": 0,
            "minSpeed": 11,
            "maxSpeed": 14,
            "spellPower": 26,
            "valMagicDef": 255,
            "valDefense": "4 90%x4"
        },
        {
            "location": "Baron Throne Room",
            "hitPoints": 4000,
            "attackMultiplier": 3,
            "attackPercent": 99,
            "attackPower": 44,
            "defense": 2,
            "magicDefense": 0,
            "minSpeed": 15,
            "maxSpeed": 15,
            "spellPower": 29,
            "valMagicDef": 255,
            "valDefense": "6 70%x5"
        },
        {
            "location": "Calbrena (Dwarf Castle 1)",
            "hitPoints": 8524,
            "attackMultiplier": 7,
            "attackPercent": 99,
            "attackPower": 96,
            "defense": 2,
            "magicDefense": 0,
            "minSpeed": 11,
            "maxSpeed": 11,
            "spellPower": 41,
            "valMagicDef": 255,
            "valDefense": "5 80%x4"
        },
        {
            "location": "Cave Bahamut",
            "hitPoints": 37000,
            "attackMultiplier": 13,
            "attackPercent": 99,
            "attackPower": 174,
            "defense": 1,
            "magicDefense": 0,
            "minSpeed": 27,
            "maxSpeed": 27,
            "spellPower": 17,
            "valMagicDef": 170,
            "valDefense": "4 0%x0"
        },
        {
            "location": "Cave Magnes",
            "hitPoints": 5000,
            "attackMultiplier": 4,
            "attackPercent": 99,
            "attackPower": 54,
            "defense": 3,
            "magicDefense": 0,
            "minSpeed": 11,
            "maxSpeed": 11,
            "spellPower": 15,
            "valMagicDef": 255,
            "valDefense": "5 0%x0"
        },
        {
            "location": "CPU (Giant 2)",
            "hitPoints": 24000,
            "attackMultiplier": 13,
            "attackPercent": 99,
            "attackPower": 174,
            "defense": 4,
            "magicDefense": 0,
            "minSpeed": 38,
            "maxSpeed": 38,
            "spellPower": 127,
            "valMagicDef": 255,
            "valDefense": "16 90%x2"
        },
        {
            "location": "Dark Imp (Tower Key)",
            "hitPoints": 597,
            "attackMultiplier": 5,
            "attackPercent": 70,
            "attackPower": 56,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 18,
            "maxSpeed": 21,
            "spellPower": 6,
            "valMagicDef": 0,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Dark Knight Cecil (Ordeals 3)",
            "hitPoints": 1000,
            "attackMultiplier": 3,
            "attackPercent": 99,
            "attackPower": 46,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 5,
            "maxSpeed": 5,
            "spellPower": 7,
            "valMagicDef": 254,
            "valDefense": "0 0%x0"
        },
        {
            "location": "D Lunar (Lunar Sub)",
            "hitPoints": 42000,
            "attackMultiplier": 11,
            "attackPercent": 85,
            "attackPower": 144,
            "defense": 4,
            "magicDefense": 0,
            "minSpeed": 30,
            "maxSpeed": 30,
            "spellPower": 36,
            "valMagicDef": 255,
            "valDefense": "16 90%x2"
        },
        {
            "location": "Dr Lugae (Lower Babil - Top)",
            "hitPoints": 18943,
            "attackMultiplier": 6,
            "attackPercent": 99,
            "attackPower": 86,
            "defense": 1,
            "magicDefense": 0,
            "minSpeed": 27,
            "maxSpeed": 27,
            "spellPower": 7,
            "valMagicDef": 0,
            "valDefense": "4 90%x4"
        },
        {
            "location": "Eblan Royalty (Upper Babil 1)",
            "hitPoints": 6000,
            "attackMultiplier": 9,
            "attackPercent": 85,
            "attackPower": 116,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 53,
            "maxSpeed": 53,
            "spellPower": 6,
            "valMagicDef": 0,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Elements (Giant 1)",
            "hitPoints": 65000,
            "attackMultiplier": 10,
            "attackPercent": 80,
            "attackPower": 128,
            "defense": 3,
            "magicDefense": 0,
            "minSpeed": 89,
            "maxSpeed": 89,
            "spellPower": 15,
            "valMagicDef": 86,
            "valDefense": "11 82%x2"
        },
        {
            "location": "Fabul Defense",
            "hitPoints": 1880,
            "attackMultiplier": 3,
            "attackPercent": 90,
            "attackPower": 36,
            "defense": 2,
            "magicDefense": 0,
            "minSpeed": 6,
            "maxSpeed": 9,
            "spellPower": 6,
            "valMagicDef": 254,
            "valDefense": "6 70%x5"
        },
        {
            "location": "Golbez (Dwarf Castle 2)",
            "hitPoints": 3002,
            "attackMultiplier": 5,
            "attackPercent": 99,
            "attackPower": 68,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 27,
            "maxSpeed": 27,
            "spellPower": 1,
            "valMagicDef": 0,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Kaipo Inn",
            "hitPoints": 302,
            "attackMultiplier": 3,
            "attackPercent": 75,
            "attackPower": 26,
            "defense": 2,
            "magicDefense": 0,
            "minSpeed": 2,
            "maxSpeed": 4,
            "spellPower": 4,
            "valMagicDef": 255,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Karate (Baron Inn 2)",
            "hitPoints": 4000,
            "attackMultiplier": 6,
            "attackPercent": 99,
            "attackPower": 86,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 4,
            "maxSpeed": 7,
            "spellPower": 12,
            "valMagicDef": 0,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Leviatan (Feymarch)",
            "hitPoints": 35000,
            "attackMultiplier": 13,
            "attackPercent": 99,
            "attackPower": 174,
            "defense": 5,
            "magicDefense": 0,
            "minSpeed": 53,
            "maxSpeed": 53,
            "spellPower": 34,
            "valMagicDef":255,
            "valDefense": "20 80%x1"
        },
        {
            "location": "Magus Sisters (Zot 1)",
            "hitPoints": 9000,
            "attackMultiplier": 5,
            "attackPercent": 80,
            "attackPower": 60,
            "defense": 2,
            "magicDefense": 0,
            "minSpeed": 7,
            "maxSpeed": 7,
            "spellPower": 11,
            "valMagicDef": 254,
            "valDefense": "5 80%x4"
        },
        {
            "location": "Milon (Ordeals 1)",
            "hitPoints": 2780,
            "attackMultiplier": 1,
            "attackPercent": 75,
            "attackPower": 19,
            "defense": 2,
            "magicDefense": 0,
            "minSpeed": 8,
            "maxSpeed": 8,
            "spellPower": 14,
            "valMagicDef": 0,
            "valDefense": "5 80%x4"
        },
        {
            "location": "Milon Z (Ordeals 2)",
            "hitPoints": 3000,
            "attackMultiplier": 3,
            "attackPercent": 99,
            "attackPower": 44,
            "defense": 1,
            "magicDefense": 0,
            "minSpeed": 9,
            "maxSpeed": 9,
            "spellPower": 31,
            "valMagicDef": 255,
            "valDefense": "4 90%x4"
        },
        {
            "location": "Mist Cave",
            "hitPoints": 465,
            "attackMultiplier": 2,
            "attackPercent": 90,
            "attackPower": 16,
            "defense": 5,
            "magicDefense": 0,
            "minSpeed": 5,
            "maxSpeed": 5,
            "spellPower": 10,
            "valMagicDef": 255,
            "valDefense": "20 80%x1"
        },
        {
            "location": "Mt Hobs",
            "hitPoints": 1250,
            "attackMultiplier": 3,
            "attackPercent": 80,
            "attackPower": 30,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 7,
            "maxSpeed": 7,
            "spellPower": 5,
            "valMagicDef": 174,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Odin (Baron Castle Basement)",
            "hitPoints": 20500,
            "attackMultiplier": 9,
            "attackPercent": 85,
            "attackPower": 116,
            "defense": 3,
            "magicDefense": 0,
            "minSpeed": 43,
            "maxSpeed": 46,
            "spellPower": 95,
            "valMagicDef": 254,
            "valDefense": "11 85%x2"
        },
        {
            "location": "Ogopogo (Lunar Core)",
            "hitPoints": 37000,
            "attackMultiplier": 11,
            "attackPercent": 99,
            "attackPower": 150,
            "defense": 4,
            "magicDefense": 0,
            "minSpeed": 38,
            "maxSpeed": 38,
            "spellPower": 127,
            "valMagicDef": 255,
            "valDefense": "16 90%x2"
        },
        {
            "location": "Pale Dim (Lunar Sub)",
            "hitPoints": 27300,
            "attackMultiplier": 11,
            "attackPercent": 85,
            "attackPower": 144,
            "defense": 5,
            "magicDefense": 0,
            "minSpeed": 40,
            "maxSpeed": 43,
            "spellPower": 31,
            "valMagicDef": 20,
            "valDefense": "5 99%x2"
        },
        {
            "location": "Plague (Lunar Sub)",
            "hitPoints": 28000,
            "attackMultiplier": 11,
            "attackPercent": 90,
            "attackPower": 146,
            "defense": 5,
            "magicDefense": 0,
            "minSpeed": 29,
            "maxSpeed": 32,
            "spellPower": 35,
            "valMagicDef": 255,
            "valDefense": "20 99%x2"
        },
        {
            "location": "Rubicant (Upper Babil 2)",
            "hitPoints": 25200,
            "attackMultiplier": 7,
            "attackPercent": 80,
            "attackPower": 88,
            "defense": 1,
            "magicDefense": 0,
            "minSpeed": 38,
            "maxSpeed": 38,
            "spellPower": 16,
            "valMagicDef": 255,
            "valDefense": "4 90%x4"
        },
        {
            "location": "Sealed Cave",
            "hitPoints": 19000,
            "attackMultiplier": 6,
            "attackPercent": 90,
            "attackPower": 84,
            "defense": 2,
            "magicDefense": 0,
            "minSpeed": 66,
            "maxSpeed": 66,
            "spellPower": 79,
            "valMagicDef": 255,
            "valDefense": "5 80%x4"
        },
        {
            "location": "Valvalis (Zot 2)",
            "hitPoints": 6000,
            "attackMultiplier": 5,
            "attackPercent": 99,
            "attackPower": 70,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 18,
            "maxSpeed": 18,
            "spellPower": 63,
            "valMagicDef": 255,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Watery Passage",
            "hitPoints": 2350,
            "attackMultiplier": 2,
            "attackPercent": 99,
            "attackPower": 22,
            "defense": 0,
            "magicDefense": 0,
            "minSpeed": 31,
            "maxSpeed": 31,
            "spellPower": 4,
            "valMagicDef": 255,
            "valDefense": "0 0%x0"
        },
        {
            "location": "Wyvern (Lunar Sub)",
            "hitPoints": 25000,
            "attackMultiplier": 12,
            "attackPercent": 90,
            "attackPower": 160,
            "defense": 5,
            "magicDefense": 0,
            "minSpeed": 43,
            "maxSpeed": 46,
            "spellPower": 8,
            "valMagicDef": 255,
            "valDefense": "20 99%x2"
        }
    ]

export default SummaryData
